phpgt/Dom

.gitignore, test/HTMLCollection.test.php, test/Helper.php
You might want to accept this one onto a new branch - or just reject it if I've got the wrong end of the stick on how the property should work.
=> Defect with HTMLDocument->forms property?

README.md
=> add packagist badge

src/HTMLCollection.php, test/HTMLCollection.test.php
Hello, I'm happy to collaborate.
I have questions:
1. Is it better to return $this->length or the prop_get_length private method?
2. What is the coding style rules?
=> Count method implementation.

src/HTMLDocument.php, test/HTMLDocument.test.php
I don't think importing the elements was a good solution, but I could not find another solution, yet.
=> Proposal: allowing constructing with DOMDocument. Issue #25.

src/Element.php, test/Element.test.php
I followed this: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest
=> Element::closest() implementation. Close issue #23

src/Element.php, test/Element.test.php, test/Helper.php
The closest method was returning the collection sorted by document order.
I haven't liked the way that I have gotten the last item of the collection.
Is there any specification to implement methods like last, first and sortBy?
=> Improvements on the closest method.

test/Element.test.php, test/Helper.php
Hi @aguimaraes 
Here I am testing to check that the "closest" element is in fact the closest in the tree, rather than any other matching element in the tree. 
I'll merge this in if it makes sense.
=> Test for false positives, for #23

circle.yml
Now Circle has updated their PHP versions, use the lastest stable PHP 7 release.
=> Use proper PHP release in circle

test/HTMLDocument.test.php
Just a little mistake in HTMLDocument tests.
=> HTMLDocument test bug fix.

src/Element.php, test/Element.test.php, test/Helper.php
Hi,
I have added getter and setter for select element.
Regards, Ognjen
=> Add value getter/setter to select element

src/Document.php, src/Element.php, src/HTMLDocument.php
Relates primarily to #46.  May be insufficient to close it though.
=> Add several return-types

src/Element.php, test/Element.test.php, test/Helper.php
This set of tests (and slight functionality implementation) brings the Element class to full DOM level 4 spec.
=> Element tests

test/Element.test.php
=> Test HTML in textContent property does not affect children

.scrutinizer.yml, circle.yml, composer.json, src/ChildNode.php, src/Element.php, src/HTMLCollection.php, src/HTMLDocument.php, src/TokenList.php
Added void return type hinting to every method that had no return type
=> Add void return types. Fixes #87

src/Document.php, test/Attr.test.php, test/DocumentFragment.test.php, test/Helper.php
Documentation examples included in this PR:
+ Attr - https://github.com/PhpGt/Dom/wiki/Classes-that-make-up-DOM#moving-an-attribute-between-elements
=> Test documentation examples

README.md
badges/shields#1700
badges/shields#1568
=> Self-hosted proxy due to Shields.io's abhorrent load times

src/NodeList.php
Answering Issue #144 
Implies minimum version PHP 7.1
=> Issue #144 - NodeList::current can return null

composer.json, composer.lock, src/Element.php, test/unit/FormTest.php, test/unit/Helper/Helper.php
Hi,
I have added checked getter/setter. This should also resolve issue #121.
Regards, Ognjen
=> "checked" getter/setter

src/Element.php, src/ParentNode.php, test/unit/FormTest.php, test/unit/Helper/Helper.php
Following on from PR #160 , this closes the remaining functionality of issue #121 - many options within a select element, and select elements that allow multiple options to be selected at once.
=> Implement multiple select options

test/unit/ElementTest.php, test/unit/FormTest.php
=> Added test to raise Element coverage to 100%

src/Element.php, src/TokenList.php, test/unit/ElementTest.php, test/unit/FormTest.php
I accidentally closed the original issue #224
I should not touch PRs before the second cup of coffee.
=> Jelmergu's Element::__debugInfo

src/Exception/HierarchyRequestError.php, src/HTMLElement/HTMLTableElement.php, test/phpunit/HTMLElement/HTMLTableElementTest.php
That was a beast. I hope I implemented everything according to the spec
=> Implement the HTMLTableElement

src/HTMLElement/HTMLTableElement.php, test/phpunit/HTMLElement/HTMLTableElementTest.php
Hi @speich ,
Please see these minor changes I've made to the HTMLTableElement tests. I'd like to hear your feedback.
Cheers,
Greg.
=> Facade table improvements

composer.json, composer.lock, src/HTMLDocument.php, test/phpunit/HTMLElement/HTMLScriptElementTest.php, test/phpunit/TestFactory/DocumentTestFactory.php
=> fix: create schema when loading HTML

.github/dependabot.yml, composer.json, composer.lock, scratch.php, src/HTMLElement.php
=> maintenance: dependabot

src/ParentNode.php, test/phpunit/ParentNodeTest.php
=> fix: introduce own implementation of prepend

README.md, test/phpunit/phpunit.xml
+ New PHPUnit config
+ HTTPS in readme.
=> Tiny tweaks

phpmd.xml, src/Element.php, test/phpunit/ElementTest.php, test/phpunit/HTMLDocumentTest.php
=> fix: use mb_encode_numericentity for #424

composer.json, composer.lock
For discussion in #424
Hi @glo71317, please can you check your work with this PR before it's merged? Once I have your sign off, I'll make it into another patch release.
Thanks,
Greg.
=> build: loosen psr/http-message

src/HTMLElement.php
=> tweak: allow select disabled property

src/DOMStringMap.php, test/phpunit/DOMStringMapTest.php
=> fix: camel case conversion for dataset

src/HTMLElement.php, test/phpunit/HTMLElement/HTMLElementTest.php, test/phpunit/HTMLElement/HTMLTextAreaElementTest.php
=> fix: textarea value property
